export const configPaths = {
  secretKeys: '/services/secretKeys',
  metricsCollection: '/services/metricsCollection',
  storageService: '/services/storage',
  smtp: '/services/smtp',
  auth: {
    base: '/services/auth',
    azureAD: '/services/auth/azureAd',
    google: '/services/auth/google',
    okta: '/services/auth/okta',
    microsoft: '/services/auth/microsoft',
    sso: '/services/auth/sso',
    oauth: '/services/auth/oauth',
  },
  aiModels: '/services/aiModels',
  slackBot: '/services/slackBot',
  db: {
    mongodb: '/services/mongodb',
    arangodb: '/services/arangodb',
    qdrant: '/services/qdrant',
  },
  keyValueStore: {
    redis: '/services/redis',
  },
  broker: {
    kafka: '/services/kafka',
  },
  aiBackend: '/services/query',
  endpoint: '/services/endpoints',
  url: {
    auth: '/services/nodejs/auth',
    storage: 'services/nodejs/storage',
    communication: '/services/nodejs/communication',
    iam: '/services/nodejs/iam',
    kb: '/services/nodejs/kb',
    es: '/services/nodejs/es',
    cm: '/services/nodejs/cm',
    frontend: '/services/frontend',
    indexing: '/services/indexing',
    connector: '/services/connector',
    query: '/services/query',
  },
  platform: {
    settings: '/services/platform/settings',
  },
};
