line-length = 88
target-version = "py310"

[lint]
select = ["E", "F", "W", "I"]
ignore = ["E501"]

[lint.per-file-ignores]
"tests/**.py" = [
  "ANN201", "ANN204", "ANN205", "PLR2004", "SIM118", "I001"
]


