import DOMPurify from 'dompurify';

/**
 * Full HTML documents keep CSS/fonts in `<head>` and illustrations in SVG.
 * DOMPurify's default fragment mode drops `<head>`, and the HTML profile
 * strips SVG, which is why a page that looks fine in a browser rendered as
 * unstyled text in record preview.
 */
const HTML_PREVIEW_CONFIG: Parameters<typeof DOMPurify.sanitize>[1] = {
  WHOLE_DOCUMENT: true,
  USE_PROFILES: { html: true, svg: true, svgFilters: true },
  ADD_TAGS: ['style', 'link', 'figure', 'figcaption', 'picture', 'source'],
  ADD_ATTR: [
    'target',
    'id',
    'class',
    'style',
    'href',
    'src',
    'srcset',
    'sizes',
    'alt',
    'title',
    'rel',
    'media',
    'type',
    'crossorigin',
    'as',
    'role',
    'aria-label',
    'aria-hidden',
    'tabindex',
    'width',
    'height',
    'viewBox',
    'xmlns',
    'fill',
    'stroke',
    'stroke-width',
    'stroke-linecap',
    'stroke-linejoin',
    'd',
    'cx',
    'cy',
    'r',
    'rx',
    'ry',
    'x',
    'y',
    'x1',
    'y1',
    'x2',
    'y2',
    'points',
    'transform',
    'opacity',
    'fill-rule',
    'clip-path',
    'clipPathUnits',
    'preserveAspectRatio',
    'gradientUnits',
    'gradientTransform',
    'offset',
    'stop-color',
    'stop-opacity',
    'mask',
    'filter',
    'font-family',
    'font-size',
    'font-weight',
    'text-anchor',
    'dominant-baseline',
    'letter-spacing',
  ],
  FORBID_TAGS: ['script', 'base', 'iframe', 'object', 'embed', 'applet', 'frame', 'frameset'],
  FORBID_ATTR: [
    'onerror',
    'onload',
    'onclick',
    'onmouseover',
    'onfocus',
    'onblur',
    'onchange',
    'onsubmit',
    'onkeydown',
    'onkeyup',
    'onkeypress',
    'onmousedown',
    'onmouseup',
    'onmousemove',
    'ontouchstart',
    'autofocus',
  ],
};

export function sanitizeHtmlPreview(rawHtml: string): string {
  return DOMPurify.sanitize(rawHtml, HTML_PREVIEW_CONFIG);
}
