import logging
import os
import textwrap
from typing import Text

FILE_CONTENT: Text = """\"\"\"WARNING: This file is auto-generated by a script.

Do not edit this file manually.
\"\"\"
import logging

from app.sources.client.google_cloud.google_cloud import (
    GoogleCloudClient,
    GoogleCloudServiceAccountConfig,
)
from google.cloud.storage.blob import Blob
from google.cloud.storage.bucket import Bucket

logger = logging.getLogger(__name__)


class GoogleCloudDataSource:
    \"\"\"Auto-generated data source class for Google Cloud Storage.

    It uses the GoogleCloudClient to interact with the GCS API.
    \"\"\"

    def __init__(self, client: GoogleCloudClient) -> None:
        \"\"\"Initialize the data source with an authenticated client.

        :param client: An instance of GoogleCloudClient
        \"\"\"
        self.client = client

    def get_all_buckets(self) -> list[Bucket]:
        \"\"\"Retrieve a list of all buckets accessible by the client.\"\"\"
        logger.info("Fetching all Google Cloud Storage buckets.")
        try:
            # Use the client wrapper, which handles API calls and returns a list.
            return self.client.get_client().list_buckets()
        except Exception:
            # The client layer already logs the exception with a traceback.
            return []

    def get_files_in_bucket(self, bucket_name: str) -> list[Blob]:
        \"\"\"Retrieve a list of all files (blobs) in a specific bucket.

        :param bucket_name: The name of the bucket to list files from.
        \"\"\"
        logger.info("Fetching files from bucket: %s", bucket_name)
        try:
            return self.client.get_client().list_blobs(bucket_name)
        except Exception:
            # The client layer already logs the exception with a traceback.
            return []

    def get_file_content(self, bucket_name: str, file_name: str) -> str:
        \"\"\"Retrieve the text content of a specific file from a bucket.

        :param bucket_name: The name of the bucket.
        :param file_name: The name (path) of the file in the bucket.
        \"\"\"
        logger.info(
            "Fetching content for file: %s from bucket: %s",
            file_name,
            bucket_name,
        )
        try:
            return self.client.get_client().download_blob_as_text(
                bucket_name, file_name,
            )
        except Exception:
            # The client layer already logs the exception with a traceback.
            return ""

    @staticmethod
    def get_config_class() -> type[GoogleCloudServiceAccountConfig]:
        \"\"\"Return the configuration class needed to build the client.

        This is used by the application to know what config to ask for.
        \"\"\"
        return GoogleCloudServiceAccountConfig
"""


def generate_data_source() -> None:
    """
    Finds the correct path and writes the FILE_CONTENT to the
    google_cloud.py data source file.
    """
    try:
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

        output_dir = os.path.join(
            base_dir, "app/sources/external/google_cloud"
        )
        output_file = os.path.join(output_dir, "google_cloud.py")

        os.makedirs(output_dir, exist_ok=True)
        logging.info(f"Ensured directory exists: {output_dir}")

        with open(output_file, "w") as f:
            f.write(textwrap.dedent(FILE_CONTENT))

        print(f"Successfully generated data source file at:\n{output_file}")

    except Exception as e:
        logging.error(f"Error during file generation: {e}", exc_info=True)
        print(f"Error generating file: {e}")


if __name__ == "__main__":
    # Configure logging for the script
    logging.basicConfig(level=logging.INFO)
    generate_data_source()
