# code-generator/google_cloud.py

import logging
import os
import textwrap

# This is the full text content that will be written into the new file.
# FILE_CONTENT has been updated to fix D212, I001, UP035, UP006,
# TRY401, and COM812 ruff errors.
FILE_CONTENT = '''
"""WARNING: This file is auto-generated by a script.

Do not edit this file manually.
"""

import logging

from google.cloud.storage.blob import Blob
from google.cloud.storage.bucket import Bucket

from app.sources.client.google_cloud.google_cloud import (
    GoogleCloudClient,
    GoogleCloudServiceAccountConfig,
)

logger = logging.getLogger(__name__)


class GoogleCloudDataSource:
    """Auto-generated data source class for Google Cloud Storage.

    It uses the GoogleCloudClient to interact with the GCS API.
    """

    def __init__(self, client: GoogleCloudClient) -> None:
        """Initialize the data source with an authenticated client.

        :param client: An instance of GoogleCloudClient
        """
        self.client = client

    def get_all_buckets(self) -> list[Bucket]:
        """Retrieve a list of all buckets accessible by the client."""
        logger.info("Fetching all Google Cloud Storage buckets.")
        try:
            # Use the specific getter for the underlying SDK client
            return self.client.get_storage_client().list_buckets()
        except Exception:
            logger.exception("Error fetching GCS buckets")
            return []

    def get_files_in_bucket(self, bucket_name: str) -> list[Blob]:
        """Retrieve a list of all files (blobs) in a specific bucket.

        :param bucket_name: The name of the bucket to list files from.
        """
        logger.info("Fetching files from bucket: %s", bucket_name)
        try:
            return self.client.get_storage_client().list_blobs(bucket_name)
        except Exception:
            logger.exception(
                "Error fetching files from GCS bucket %s", bucket_name,
            )
            return []

    def get_file_content(self, bucket_name: str, file_name: str) -> str:
        """Retrieve the text content of a specific file from a bucket.

        :param bucket_name: The name of the bucket.
        :param file_name: The name (path) of the file in the bucket.
        """
        logger.info(
            "Fetching content for file: %s from bucket: %s",
            file_name,
            bucket_name,
        )
        try:
            return self.client.get_storage_client().download_blob_as_text(
                bucket_name, file_name,
            )
        except Exception:
            logger.exception(
                "Error fetching content for %s from %s",
                file_name,
                bucket_name,
            )
            return ""

    @staticmethod
    def get_config_class() -> type[GoogleCloudServiceAccountConfig]:
        """Return the configuration class needed to build the client.

        This is used by the application to know what config to ask for.
        """
        return GoogleCloudServiceAccountConfig
'''


def generate_data_source():
    """
    Finds the correct path and writes the FILE_CONTENT to the
    google_cloud.py data source file.
    """
    try:
        # This script is in 'backend/python/code-generator/'
        # We need to go up one level to 'backend/python/'
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

        # Define the output directory and file path
        output_dir = os.path.join(base_dir, "app/sources/external/google_cloud")
        output_file = os.path.join(output_dir, "google_cloud.py")

        # Create the directory if it doesn't exist
        os.makedirs(output_dir, exist_ok=True)
        logging.info(f"Ensured directory exists: {output_dir}")

        # Write the main file content
        with open(output_file, "w") as f:
            # Dedent the content to remove leading indentation
            f.write(textwrap.dedent(FILE_CONTENT))

        print(f"Successfully generated data source file at:\n{output_file}")

    except Exception as e:
        logging.error(f"Error during file generation: {e}", exc_info=True)
        print(f"Error generating file: {e}")


if __name__ == "__main__":
    # Configure logging for the script
    logging.basicConfig(level=logging.INFO)
    generate_data_source()
